version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db   # define the address/hostname of the mysql server eg mysql container name.
      PMA_USER: root # this is the root user to login on startup
      PMA_PASSWORD: password # use the root password to login on startup.
    depends_on:
      - db
  
  php:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./web/src:/var/www/html/
      
      

